cakephp/cakephp.org

config/site.php
src/Template/Element/business-solutions/development.ctp
src/Template/Element/trademark/universal-considerations.ctp

Wording fixes

---

README.md

It tries to solve #42 
@ravage84 can you give me your thoughts? Thanks.

Refs #42 adding the basics to the readme

---

webroot/css/custom.css

Refs #36 adding width 100% to carousel images

---

config/bootstrap.php
src/Locale/Showcase.pot
src/Locale/Users.pot
src/Locale/default.pot
src/Locale/ja_JP/default.po

Reopen #34.
Re-translated "Get Involved" into Japanese.
Take @ravage84's advice.

Translate new website into Japanese

---

config/routes.php
src/Controller/AppController.php
src/Template/Element/Layout/default/menu/menu.ctp
webroot/css/custom.css

It solves #55 
Thanks to @lorenzo for his nice routing trick: https://github.com/steinkel/cakefest2016/blob/advanced/config/routes.php
It looks like this:
closed
opened

Refs #55 adding language selector to top menu. Thanks to @lorenzo.

---

composer.json
composer.lock
config/app.default.php
src/Template/Element/home/cake.ctp

Update version number to 3.3.0

---

webroot/css/custom.css

Now we have a total red languange selector ;)

Refs #55 fixing language selector colors

---

src/Locale/fr_FR/default.po

Please do not merge, work in progress.
@HavokInspiration @antograssiot Just a start, if you don't know what to do during holidays.... 😄

start fr translation

---

src/Template/Element/Layout/default/footer/menu/column_one.ctp
src/Template/Element/Layout/default/menu/mobile_menu.ctp
src/Template/Element/Layout/default/navbar.ctp
src/Template/Element/home/share.ctp

**src/Template/Element/Layout/default/navbar.ctp**
(mobile)
**src/Template/Element/Layout/default/menu/mobile_menu.ctp**
**src/Template/Element/home/share.ctp**
**src/Template/Element/Layout/default/footer/menu/column_one.ctp**

Linking to localized pages

---

src/Template/Element/trademark/general-information.ctp

There were a few red links that should have been blue.
See cakephp/docs#4373

Make links blue.

---

src/Template/Pages/videos.ctp

- Add link to the channel
- Make the top video the most recent one video uploaded to the channel

Videos page improvements

---

src/Template/Pages/videos.ctp

Videos page fix

---

webroot/.well-known/security.txt

As discussed with @ADmad .
For the time being, we only have a contact mail.

Add a security.txt to the webroot under .well-known as proposed by https://securitytxt.org/

---

config/site.php

I don't work at Sentry anymore, and the illustration gigs are pretty sparse these days.

Update my Bio.

---

config/site.php

Update CakeDC and StickerYou links to open in new tabs

Update sponsor links to open in new tabs

---

config/site.php

Removed inactive team members: Jippi jrbasso cgtag beakman antograssiot

Remove inactive team members

---

webroot/css/style.css

Change font weight for header tags.

---

src/View/Helper/MeetupsHelper.php

https://github.com/cakephp/cakephp.org/issues/167
I don't have a way to test this, but the logic should work.

Allow meetups within the past day to show

---

webroot/css/responsive.css

fix showcase carousel on mobile

---

webroot/css/responsive.css

only first child after fix https://github.com/cakephp/cakephp.org/issues/176
If you need to add something remove write

add space to banner

---

webroot/css/responsive.css

fix issue https://github.com/cakephp/cakephp.org/issues/178

update titles for mobile device

---

webroot/css/style.css

fix issue https://github.com/cakephp/cakephp.org/issues/180

fix hover dropdown menu item

---

webroot/css/style.css

fix issue https://github.com/cakephp/cakephp.org/issues/183

centering github buttons

---

src/Template/Element/Layout/default/footer.ctp
src/Template/Element/Layout/default/footer/login_form.ctp
webroot/css/custom.css
webroot/css/responsive.css

fix issue https://github.com/cakephp/cakephp.org/issues/186

footer column update

---

webroot/css/style.css

fix issue https://github.com/cakephp/cakephp.org/issues/226

add indent to banner on mobile & tablet

---

src/Template/Element/Layout/default/footer.ctp

fix issue https://github.com/cakephp/cakephp.org/issues/231

fix copyright

---

src/Template/Element/home/cake.ctp

Change Download to Install

---

src/Template/Element/business-solutions/sidebar.ctp

https://github.com/cakephp/cakephp.org/issues/261

Accessibility - update list

---

src/Template/Element/home/contact_info.ctp

https://cakephp.org/pages/business-solutions

Accessibility - update contact info

---

config/routes.php

Move custom routes above general pages route.

---

webroot/css/style.css

https://cakephp.org/pages/business-solutions

Accessibility - update color contrast

---

src/Template/Element/Layout/default/footer.ctp
webroot/css/responsive.css

https://github.com/cakephp/cakephp.org/issues/275

fix footer social media

---

src/Template/Layout/default.ctp

resolve https://github.com/cakephp/cakephp.org/issues/292

update google font

---

src/Template/Element/Layout/default/menu/mobile_menu.ctp

resolve https://github.com/cakephp/cakephp.org/issues/295

Accessibility add link name

---

src/Template/Element/get-involved/get-involved.ctp
webroot/css/custom.css

resolve https://github.com/cakephp/cakephp.org/issues/305

Accessibility update color contrast

---

src/Template/Element/trademark/flags.ctp

Accessibility update color contrast (btn)

---

webroot/css/style.css

fix form input

---

webroot/css/responsive.css

resolve https://github.com/cakephp/cakephp.org/issues/318

fix content goes beyond block boundaries

---

src/Template/Element/home/cakefest_online.ctp

resolve https://github.com/cakephp/cakephp.org/issues/322

Accessibility add title to banner link

---

src/Template/Pages/team.ctp

resolve https://github.com/cakephp/cakephp.org/issues/329

Accessibility add link name (modal)

---

src/Template/Element/Layout/default/footer/social_links.ctp

IRC is pretty dead and I don't feel good about recommending new people join freenode.net given the current stewardship of that service. Fix the slack inviter app link as it is currently broken.
cc @steinkel

Add mastodon and remove IRC

---

config/site.php
src/Template/Element/Layout/default/footer/social_links.ctp

I missed adding mastodon to the community link lists.

Add mastodon Part 2

---

src/Template/Pages/team.ctp

fix team social icons

---

config/site.php
src/Template/Element/get-involved/get-help.ctp
src/Template/Element/get-involved/get-involved.ctp

It's neither manned or bridged to the other support forums anymore.

Remove references to the IRC channel.

---

src/Template/Element/home/cake.ctp
src/Template/Element/home/share.ctp
src/Template/Element/home/summary.ctp
src/Template/Element/home/support.ctp
src/Template/Element/home/whats_new.ctp

resolve https://github.com/cakephp/cakephp.org/issues/352

add alt description to images

---

config/site.php

fix sponsors alt tag

---

webroot/css/style.css

resolve https://github.com/cakephp/cakephp.org/issues/368

ui small update hero section on mobile

---

webroot/css/responsive.css

resolve https://github.com/cakephp/cakephp.org/issues/371

small ui update on sponsors block

---

templates/Pages/home.php
templates/element/home/whats_new.php

Refresh the content on the main site.

Update landing page content for 5.1
